### ISSUE TITLE
Allow "default" deploy variables to be set

### ISSUE THREAD

**Issue by hybby** [jacob-meacham/serverless-plugin-deploy-environment#7]
I love the idea of this plugin.  It solves a problem that I'm currently wrestling with.

From your usage information, you show the following:

```
custom:
  deploy:
    variables:
      dev:
        role: "devRole"
        streamArn: "devStream"
      staging:
        role: "stagingRole"
        streamArn: "stagingStream"
    environments:
      # These will be added to all environments
      default:
        LAMBDA_LOG_LEVEL: info
        LAMBDA_REGION: ${self:provider.region} # All references are resolved
        LAMBDA_ES_HOST:
          'Fn::GetAtt': [ 'ESCluster', 'DomainEndpoint' ]
      dev:
        LAMBDA_ES_HOST: localhost
```

This tells me that you support "default" environment variables that are added to "all" environments, unless overriden, which is amazing.

I'd be really interested for this "default" behaviour to take place at the "variables" step as well, so that I could provide a "default" development IAM role, but potentially override it for a Production environment.

Is that something that your plugin currently supports, or a feature that you could potentially adopt?

Thanks for writing this, it seems really cool!
Drew
